require 'paperclip_database_attachments_responder/version'
require 'paperclip_database_attachments_responder/middleware'
require 'paperclip_database_attachments_responder/railtie'
require 'paperclip_database_attachments_responder/paperclip_database_patcher'